### ISSUE TITLE
Build command fail

### ISSUE THREAD

**Issue by juunone** [ambientlight/amplify-cli-action#11]
hi i have question for use this amplify action
i change to build command to `build_command: 'yarn build:dev'` like this.
i have multiple build scripts in package.json 
- yarn build
- yarn build:dev
- yarn build:prod

it has each have other build scripts
and i want to publish with yarn:dev script but when i try action
it only use yarn build..
how do i. change build_command ? not only yarn build

second i try to `project_dir`
`amplify` and `amplify_rnd` 
i have configure and publish with `project_dir: 'amplify_rnd'`
but it only look `amplify` 
is am i wrong with use project_dir?
amplfiy_rnd have proejct-config.json and "BuildCommand": "yarn build:rnd" 

i will wait for answer
thanks.

**Comment by ambientlight** [comment]
@juunone: will try to give you an answer this weekend, thanks

**Comment by juunone** [comment]
@ambientlight thanks for answering
i will wait for response
thanks.

**Comment by ambientlight** [comment]
> how do i. change build_command ? not only yarn build

You can use just a bare bash script inside github actions like, add additional step like:

```
- name: 'Build the code'
        run: |
          yarn build
          yarn build:dev
          yarn build:prod
          // and then either run publish directly, or use another step from `amplify_cli_actions` 
          amplify publish
``` 

> 
second i try to project_dir
amplify and amplify_rnd
i have configure and publish with project_dir: 'amplify_rnd'
but it only look amplify
is am i wrong with use project_dir?

Hm, how did you configure here?

**Comment by juunone** [comment]
@ambientlight 

```
- name: Install node packages
      run: |
        yarn install     
```

```
uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_cli_version: '3.17.0'
        amplify_env: rnd
        amplify_command: publish
        amplify_arguments: '-c'
        build_command: 'yarn build:dev'
```

i use like this. 
with amplify-cli-action but when i build with `build_command` is only build with `yarn build` not yarn build:dev
how do i change build_command ?

**Comment by ambientlight** [comment]
> how do i change build_command ?

One approach you can try is to build yourself and then use amplify push command, something like:

```
    - name: build
      run: |
        yarn build:dev
        
    - name: deploy
      uses: ambientlight/amplify-cli-action@amplify_command
      with:
        amplify_command: push
        amplify_env: rnd
        amplify_cli_version: '3.17.0'
      env:
        AWS_ACCESS_KEY_ID: ...
        AWS_SECRET_ACCESS_KEY: ...
        AWS_REGION: ...
```

Another one you can try is to rename your commands and then chaining them, inside `build_command` change `yarn build:dev` to `yarn build_dev && yarn build_prod`

**Comment by juunone** [comment]
package.json
```
"build": "PUBLIC_URL=https://www.test.net react-app-rewired build",
"build_rnd": "npm rebuild node-sass && PUBLIC_URL=https://rnd.test.net GENERATE_SOURCEMAP=false NODE_OPTIONS=--max_old_space_size=8192 node_modules/.bin/env-cmd -f .env.development react-app-rewired build",
"build:dev": "npm rebuild node-sass && PUBLIC_URL=https://dev.test.net GENERATE_SOURCEMAP=false NODE_OPTIONS=--max_old_space_size=8192 node_modules/.bin/env-cmd -f .env.development react-app-rewired build",
"build:stg": "npm rebuild node-sass && PUBLIC_URL=https://stg.test.net GENERATE_SOURCEMAP=false NODE_OPTIONS=--max_old_space_size=8192 node_modules/.bin/env-cmd -f .env.development react-app-rewired build",
```

yml
```
- name: Build and amplify cli publish to cloud front to prod
      if: contains(github.ref, 'github-action-deploy') 
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_cli_version: '3.17.0'
        amplify_env: rnd
        amplify_command: publish
        amplify_arguments: '-c'
        build_command: 'yarn build:rnd'
```

sorry for my question detail. explain more detail to you
i have three each scripts and amplify env.
than i want to deploy each env with script.

when i use amplify-cli-action@0.2.1 in build_command paremeter with that example yml.
it's only use `build` scripts in package.json not `build:rnd`
how to i solve this problem?

i think rename and chaining is not solution.
it's just not support other build scripts except build

**Comment by ambientlight** [comment]
@juunone: If I understood your setup, you want to trigger conditional build command, that is `build:dev` for dev stage, `build:prod` for prod stage with amplify project-config.json setup accordingly, this is not on `amplify-cli-action` side, you may repost this to `amplify-cli` to seek help there

**Comment by juunone** [comment]
is amplify-cli-action `build_command` only support package.json script with `yarn build` command?
it's just run only `yarn build` when i build_command `yarn build:dev` or `yarn build:prod`

**Comment by ambientlight** [comment]
@juunone: I am sorry for the confusion, `build_command` was removed as the configure command changed in https://github.com/ambientlight/amplify-cli-action/commit/86d8412c2a97c31bdfa0867d731d82802ac24806#diff-b958f585a04af5ee2087610ea7180f34

`amplify/.config/project-config.json` committed will be used by this action (rather then rewritten in `amplify configure` in first version of this action)
It was still left out in `action.yaml` so that the steps won't fail after action get updated.

So, to reiterate, `build_command` is no longer managed by this action, if you find your local machine behavior different from whats happening here in CI, this needs to be further investigated by likely it is not on this action side

**Comment by juunone** [comment]
@ambientlight i understand it. thanks
because i used `build_command` and than i think it overwrite in `project-config.json`'s `BuildCommand` 
but it does not.
github action CI is well building in with project-config.json

than you know want i want help things.
i want to conditional build. like this

```
if: contains(github.ref, 'develop') 
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_cli_version: '3.17.0'
        amplify_env: dev
        amplify_command: publish
        amplify_arguments: '-c'
        build_command: 'yarn build:dev'
```

```
if: contains(github.ref, 'stg') 
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_cli_version: '3.17.0'
        amplify_env: stg
        amplify_command: publish
        amplify_arguments: '-c'
        build_command: 'yarn build:stg'
```
how do i build with multiple command?
