### ISSUE TITLE
./amplify/.config/local-env-info.json: No such file or directory

### ISSUE THREAD

**Issue by thisismydesign** [ambientlight/amplify-cli-action#13]
Hey, I'm getting this error with the `configure` command.

```
using amplify available at PATH
/usr/local/bin/amplify
amplify version Scanning for plugins...
Plugin scan successful
4.27.0
/entrypoint.sh: line 62: ./amplify/.config/local-env-info.json: No such file or directory
```

My job:
```
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [lint, test-unit, test-e2e, build]
    steps:
    - name: configure amplify
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_command: configure
        amplify_env: prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
```
