### ISSUE TITLE
prod environment does not exist, consider using add_env command instead

### ISSUE THREAD

**Issue by hamzajaved12** [ambientlight/amplify-cli-action#14]

**Comment by hamzajaved12** [comment]
When I use 
amplify_env: prod it gives the above error
but when I used amplify_env: dev it works fine why?

**Comment by sar** [comment]
Environment names are arbitrary but must exist in AWS, by default `$ amplify init` command only instantiates a `dev` env. 

While [README.md](https://github.com/ambientlight/amplify-cli-action/blob/master/README.md) for Github Actions template mentions `prod` as the default target, you're still required to add it to your AWS resource.

```yaml
    - name: configure amplify
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_command: configure
        amplify_env: prod       # Environment name that exists in CloudFormation Amplify target

    - name: deploy
      uses: ambientlight/amplify-cli-action@0.3.0
      with:
        amplify_command: publish
        amplify_env: prod      # Environment name that exists in CloudFormation Amplify target
```

See [Amplify Docs](https://docs.amplify.aws/cli/teams/overview) on adding environments using the command `$ amplify env add`.
