### ISSUE TITLE
Task failure due to not automatically selecting authentication method

### ISSUE THREAD

**Issue by koterthecoder** [ambientlight/amplify-cli-action#21]
After months of successful deployments, today I noticed that my `amplify configure` task was failing.

Here is the output I'm getting for this plugin. 

It appears that the 'authentication method' is being requested and not automatically selecting 'AWS access keys.'

![image](https://user-images.githubusercontent.com/42450792/115120435-7fde4900-9f7b-11eb-9399-69bc3b27149b.png)

Here is the yaml for the task
```
    - name: configure amplify [DEV]
      if: ${{ github.event_name == 'push' }}
      uses: ambientlight/amplify-cli-action@0.2.1
      with:
        amplify_command: configure
        amplify_env: dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
```
