### ISSUE TITLE
Action amplify CLI version

### ISSUE THREAD

**Issue by MateoKruk** [ambientlight/amplify-cli-action#25]
When using the action I get the following error:

![image](https://user-images.githubusercontent.com/9438362/124828135-3f281780-df4d-11eb-801e-0f4d39ef6f74.png)

**Comment by applyinnovations** [comment]
For some reason ambientlight/amplify-cli-action@0.3.0 is still using amplify version 4.52.0 however the latest published version on [npm](https://www.npmjs.com/package/@aws-amplify/cli) is 5.5.0. According to the readme isn't amplify-cli-action supposed to be pulling the `@latest` from npm? This has broken my deployment workflows because there are breaking changes between version 4 and version 5 of the amplify cli.

**Comment by applyinnovations** [comment]
The Dockerfile in the master branch https://github.com/ambientlight/amplify-cli-action/blob/master/Dockerfile runs 
```npm install --global --unsafe-perm @aws-amplify/cli@latest```
however only version 4.52.0 is used not 5.5.0. 

On my local machine:
```
$ npm view @aws-amplify/cli@latest
@aws-amplify/cli@5.5.0 | Apache-2.0 | deps: 68 | versions: 958
```
Anyone know why our actions are still using an old version?

**Comment by etaytch** [comment]
Hey all,
I'm having the same issue.
Is there an ETA for this?
🙏 🙏

**Comment by applyinnovations** [comment]
I can confirm that specifying the amplify version within your workflow can be used as a temporary fix.
```
    uses: ambientlight/amplify-cli-action@0.3.0
    with:
        amplify_cli_version: '5.6.0'
```

**Comment by applyinnovations** [comment]
Even better is to do the following:
```
env:
  AMPLIFY_CLI_VERION: 'latest'
jobs:
    init:
        - name: Amplify configure
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_cli_version: ${{ env.AMPLIFY_CLI_VERION }}
```
