### ISSUE TITLE
amplify_command: add_env returns message: Using default provider  undefined  

### ISSUE THREAD

**Issue by dadamsGS** [ambientlight/amplify-cli-action#28]
Not sure what I am doing wrong here but I have been trying to get amplify-cli-action working for the last three days.

local-env-info.json is added and not gitignored. I did not see anything in the README regarding the need to do this and it seems antithetical to using amplify-cli as they explicitly add it to the gitignore.

The error I am running into is:
```
Using default provider  undefined
init failed
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:22:36
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:21:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:5:58)
```

I do have a project-config.json as well that is also not gitignored.

The command that is getting executed is (GHA output):
```
Run ambientlight/amplify-cli-action@0.3.0
  with:
    amplify_command: add_env
    amplify_env: greentest
    amplify_cli_version: 3.17.1-alpha.35
    delete_lock: false
    source_dir: src
    distribution_dir: dist
    build_command: npm run build
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_REGION: us-east-2
```

Any direction on this would be really helpful.
