### ISSUE TITLE
Feature request: Provide command arguments

### ISSUE THREAD

**Issue by Silind** [ambientlight/amplify-cli-action#5]
## Feature
Provide arguments to the amplify command.

## Example
```yml
- name: deploy
  uses: ambientlight/amplify-cli-action@0.2.0
    with:
      amplify_command: publish
      amplify_argument: c
      amplify_env: prod
      build_command: 'npm run build'
```

This would be equivalent to using the command `amplify publish -c`.

**Comment by ambientlight** [comment]
@Silind: yes, this would be great, will try addressing this soon, thanks!

**Comment by ambientlight** [comment]
should be available in `0.2.1` like:

```yaml
- name: deploy
  uses: ambientlight/amplify-cli-action@0.2.1
    with:
      amplify_command: publish
      amplify_arguments: '-c'
      amplify_env: prod
      build_command: 'npm run build'
```

closing this one, feel free to reopen if there are issues / questions
